# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\x0c\x65mbedding.v1\"\x1d\n\x0b\x44\x65nseVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"/\n\x0cSparseVector\x12\x0f\n\x07indices\x18\x01 \x03(\r\x12\x0e\n\x06values\x18\x02 \x03(\x02\"{\n\x0eQueryEmbedding\x12(\n\x05\x64\x65nse\x18\x01 \x01(\x0b\x32\x19.embedding.v1.DenseVector\x12*\n\x06sparse\x18\x02 \x01(\x0b\x32\x1a.embedding.v1.SparseVector\x12\x13\n\x0btoken_count\x18\x03 \x01(\r\"5\n\x11\x45mbedQueryRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"i\n\x12\x45mbedQueryResponse\x12/\n\tembedding\x18\x01 \x01(\x0b\x32\x1c.embedding.v1.QueryEmbedding\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x0b\n\x03\x64im\x18\x03 \x01(\r\"8\n\x13\x45mbedQueriesRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"l\n\x14\x45mbedQueriesResponse\x12\x30\n\nembeddings\x18\x01 \x03(\x0b\x32\x1c.embedding.v1.QueryEmbedding\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x0b\n\x03\x64im\x18\x03 \x01(\r2\xba\x01\n\x10\x45mbeddingService\x12O\n\nEmbedQuery\x12\x1f.embedding.v1.EmbedQueryRequest\x1a .embedding.v1.EmbedQueryResponse\x12U\n\x0c\x45mbedQueries\x12!.embedding.v1.EmbedQueriesRequest\x1a\".embedding.v1.EmbedQueriesResponseB\x1aZ\x18\x65mbedding/v1;embeddingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030embedding/v1;embeddingv1'
  _globals['_DENSEVECTOR']._serialized_start=33
  _globals['_DENSEVECTOR']._serialized_end=62
  _globals['_SPARSEVECTOR']._serialized_start=64
  _globals['_SPARSEVECTOR']._serialized_end=111
  _globals['_QUERYEMBEDDING']._serialized_start=113
  _globals['_QUERYEMBEDDING']._serialized_end=236
  _globals['_EMBEDQUERYREQUEST']._serialized_start=238
  _globals['_EMBEDQUERYREQUEST']._serialized_end=291
  _globals['_EMBEDQUERYRESPONSE']._serialized_start=293
  _globals['_EMBEDQUERYRESPONSE']._serialized_end=398
  _globals['_EMBEDQUERIESREQUEST']._serialized_start=400
  _globals['_EMBEDQUERIESREQUEST']._serialized_end=456
  _globals['_EMBEDQUERIESRESPONSE']._serialized_start=458
  _globals['_EMBEDQUERIESRESPONSE']._serialized_end=566
  _globals['_EMBEDDINGSERVICE']._serialized_start=569
  _globals['_EMBEDDINGSERVICE']._serialized_end=755
# @@protoc_insertion_point(module_scope)
