# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reranker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'reranker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ereranker.proto\x12\x0breranker.v1\"*\n\x0eRerankDocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x86\x01\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12.\n\tdocuments\x18\x02 \x03(\x0b\x32\x1b.reranker.v1.RerankDocument\x12\x12\n\x05top_n\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x10return_documents\x18\x04 \x01(\x08\x42\x08\n\x06_top_n\"H\n\x0eRankedDocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\r\x12\r\n\x05score\x18\x03 \x01(\x01\x12\x0c\n\x04text\x18\x04 \x01(\t\"U\n\x0eRerankResponse\x12,\n\x07results\x18\x01 \x03(\x0b\x32\x1b.reranker.v1.RankedDocument\x12\x15\n\rmodel_version\x18\x02 \x01(\t2T\n\x0fRerankerService\x12\x41\n\x06Rerank\x12\x1a.reranker.v1.RerankRequest\x1a\x1b.reranker.v1.RerankResponseB\x18Z\x16reranker/v1;rerankerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reranker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026reranker/v1;rerankerv1'
  _globals['_RERANKDOCUMENT']._serialized_start=31
  _globals['_RERANKDOCUMENT']._serialized_end=73
  _globals['_RERANKREQUEST']._serialized_start=76
  _globals['_RERANKREQUEST']._serialized_end=210
  _globals['_RANKEDDOCUMENT']._serialized_start=212
  _globals['_RANKEDDOCUMENT']._serialized_end=284
  _globals['_RERANKRESPONSE']._serialized_start=286
  _globals['_RERANKRESPONSE']._serialized_end=371
  _globals['_RERANKERSERVICE']._serialized_start=373
  _globals['_RERANKERSERVICE']._serialized_end=457
# @@protoc_insertion_point(module_scope)
