# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import reranker_pb2 as reranker__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reranker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RerankerServiceStub:
    """Синхронное переупорядочивание документов по релевантности запросу
    (cross-encoder BAAI/bge-reranker-v2-m3). Полностью изолировано от
    EmbeddingService: отдельный пакет и отдельный сервис. Каждый вызов ОБЯЗАН
    нести gRPC deadline.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Rerank = channel.unary_unary(
                '/reranker.v1.RerankerService/Rerank',
                request_serializer=reranker__pb2.RerankRequest.SerializeToString,
                response_deserializer=reranker__pb2.RerankResponse.FromString,
                _registered_method=True)


class RerankerServiceServicer:
    """Синхронное переупорядочивание документов по релевантности запросу
    (cross-encoder BAAI/bge-reranker-v2-m3). Полностью изолировано от
    EmbeddingService: отдельный пакет и отдельный сервис. Каждый вызов ОБЯЗАН
    нести gRPC deadline.
    """

    def Rerank(self, request, context):
        """Unary: query + N документов → те же документы, отранжированные по убыванию
        релевантности (с учётом top_n). Fail-fast: любой невалидный вход →
        INVALID_ARGUMENT; reranker выключен/не готов → UNAVAILABLE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RerankerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rerank,
                    request_deserializer=reranker__pb2.RerankRequest.FromString,
                    response_serializer=reranker__pb2.RerankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reranker.v1.RerankerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reranker.v1.RerankerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RerankerService:
    """Синхронное переупорядочивание документов по релевантности запросу
    (cross-encoder BAAI/bge-reranker-v2-m3). Полностью изолировано от
    EmbeddingService: отдельный пакет и отдельный сервис. Каждый вызов ОБЯЗАН
    нести gRPC deadline.
    """

    @staticmethod
    def Rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reranker.v1.RerankerService/Rerank',
            reranker__pb2.RerankRequest.SerializeToString,
            reranker__pb2.RerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
