# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embedding_pb2 as embedding__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub:
    """Синхронный эмбеддинг поисковых запросов (dense + sparse) моделью BGE-M3.
    Владелец контракта — embedding-service. Клиент (retrieval-service) —
    tolerant. Каждый вызов ОБЯЗАН нести gRPC deadline.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedQuery = channel.unary_unary(
                '/embedding.v1.EmbeddingService/EmbedQuery',
                request_serializer=embedding__pb2.EmbedQueryRequest.SerializeToString,
                response_deserializer=embedding__pb2.EmbedQueryResponse.FromString,
                _registered_method=True)
        self.EmbedQueries = channel.unary_unary(
                '/embedding.v1.EmbeddingService/EmbedQueries',
                request_serializer=embedding__pb2.EmbedQueriesRequest.SerializeToString,
                response_deserializer=embedding__pb2.EmbedQueriesResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer:
    """Синхронный эмбеддинг поисковых запросов (dense + sparse) моделью BGE-M3.
    Владелец контракта — embedding-service. Клиент (retrieval-service) —
    tolerant. Каждый вызов ОБЯЗАН нести gRPC deadline.
    """

    def EmbedQuery(self, request, context):
        """Unary: один запрос → один вектор. Fail-fast: битый вход → INVALID_ARGUMENT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedQueries(self, request, context):
        """Batch: N запросов → N векторов. Порядок embeddings СТРОГО совпадает
        с порядком texts (embeddings[i] соответствует texts[i]). Fail-fast:
        любой невалидный элемент батча → INVALID_ARGUMENT для всего вызова.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedQuery,
                    request_deserializer=embedding__pb2.EmbedQueryRequest.FromString,
                    response_serializer=embedding__pb2.EmbedQueryResponse.SerializeToString,
            ),
            'EmbedQueries': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedQueries,
                    request_deserializer=embedding__pb2.EmbedQueriesRequest.FromString,
                    response_serializer=embedding__pb2.EmbedQueriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.v1.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('embedding.v1.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService:
    """Синхронный эмбеддинг поисковых запросов (dense + sparse) моделью BGE-M3.
    Владелец контракта — embedding-service. Клиент (retrieval-service) —
    tolerant. Каждый вызов ОБЯЗАН нести gRPC deadline.
    """

    @staticmethod
    def EmbedQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.v1.EmbeddingService/EmbedQuery',
            embedding__pb2.EmbedQueryRequest.SerializeToString,
            embedding__pb2.EmbedQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedQueries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.v1.EmbeddingService/EmbedQueries',
            embedding__pb2.EmbedQueriesRequest.SerializeToString,
            embedding__pb2.EmbedQueriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
